export enum CouponType {

    RESTURANTS = "RESTURANTS", 
    ELECTRICITY = "ELECTRICITY", 
    FOOD = "FOOD",
    HEALTH = "HEALTH",
    SPORTS = "SPORTS", 
    CAMPING = "CAMPING", 
    TRAVELLING = "TRAVELLING"
}